### ISSUE TITLE
error on installing or enabling 

### ISSUE THREAD

**Issue by gubuntu** [shivareddyiirs/QRealTime#10]
Couldn't load plugin 'QRealTime' due to an error when calling its classFactory() method 

FileNotFoundError: [Errno 2] No such file or directory: 'python3': 'python3' 
Traceback (most recent call last):
  File "/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/QRealTime/QRealTime.py", line 50, in 
    from pyxform.builder import create_survey_element_from_dict
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 665, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pyxform'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/QRealTime/QRealTime.py", line 54, in 
    subprocess.call(['python3', '-m', 'pip', 'install','pyxform'])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python3': 'python3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 337, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/QRealTime/__init__.py", line 34, in classFactory
    from .QRealTime import QRealTime
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 665, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/QRealTime/QRealTime.py", line 58, in 
    subprocess.call(['python3', '-m', 'pip', 'install','pyxform','--user'])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python3': 'python3'

Python version: 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] 
QGIS version: 3.2.0-Bonn Bonn, exported 

Python Path:
/Applications/QGIS3.app/Contents/MacOS/../Resources/python
/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/mmqgis/forms
/data/CapeTownMarathonGIS/2018

**Comment by shivareddyiirs** [comment]
Please install pyxform  manually to your python 3 . 
It should solve your problem.

**Comment by gubuntu** [comment]
thanks, I tried pip install pyxform but QGIS 3 doesn't pick it up (on a Mac with the standard QGIS install)

**Comment by shivareddyiirs** [comment]
try pip3 install pyxform because pip would install to python 2.


Thanks & Regards
Shiva Reddy K.
Scientist/Engineer 'SD'
Indian Institute of Remote Sensing,
Indian Space Research Organisation
Department of Space
4-Kalidas Road
Dehradun
mobile: 0135-2524126

**Comment by gubuntu** [comment]
thanks, that did the trick
