### ISSUE TITLE
I don't get the data neither in the table of attributes nor the geometry

### ISSUE THREAD

**Issue by maracarolinarojas** [shivareddyiirs/QRealTime#45]
**I don't get the data neither in the table of attributes nor the geometry**
I connect to the server and download the form and its load the structure of the form in the attribute table but no data. I prepare the form in ODK Build. I tried it in the stable version and it works as long as it doesn't have grouped fields. However, in the experimental version it gives me a python error.

**Goto View-->Panels-->Log Message**
2020-05-15T08:01:54     INFO    C:/Users/Mara/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QRealTime\i18n\QRealTime_es.qm
2020-05-15T08:01:54     INFO    None
2020-05-15T08:01:54     INFO    None
2020-05-15T08:03:42     INFO    key capturedbuild_Conociendo-odk-rev_1589495584None
2020-05-15T08:03:42     INFO    [, , , , , , , , , , , , ]None
2020-05-15T08:03:42     INFO    {'nodeset': '/data/meta/instanceID', 'type': 'string', 'readonly': 'true()', 'calculate': "concat('uuid:', uuid())"}None
2020-05-15T08:03:42     INFO    attrib type isstring
2020-05-15T08:03:42     INFO    first attributeinstanceIDNone
2020-05-15T08:03:42     INFO    creating new field:instanceIDNone
2020-05-15T08:03:42     INFO    Reached HiddenNone
2020-05-15T08:03:42     INFO    setting hidden widgetNone
2020-05-15T08:03:42     INFO    {'nodeset': '/data/apellido', 'type': 'string', 'required': 'true()', '{http://openrosa.org/javarosa}requiredMsg': "jr:itext('/data/apellido:requiredMsg')", '{http://openrosa.org/javarosa}constraintMsg': "jr:itext('/data/apellido:constraintMsg')"}None
2020-05-15T08:03:42     INFO    attrib type isstring
2020-05-15T08:03:42     INFO    first attributeapellidoNone
2020-05-15T08:03:42     INFO    creating new field:apellidoNone
2020-05-15T08:03:42     INFO    'type'None
2020-05-15T08:03:42     INFO    {'nodeset': '/data/nombre', 'type': 'string', 'required': 'true()', '{http://openrosa.org/javarosa}requiredMsg': "jr:itext('/data/nombre:requiredMsg')", '{http://openrosa.org/javarosa}constraintMsg': "jr:itext('/data/nombre:constraintMsg')"}None
2020-05-15T08:03:42     INFO    attrib type isstring
2020-05-15T08:03:42     INFO    first attributenombreNone
2020-05-15T08:03:42     INFO    creating new field:nombreNone
2020-05-15T08:03:42     INFO    'type'None
2020-05-15T08:03:42     INFO    {'nodeset': '/data/edad', 'type': 'int', 'required': 'true()', '{http://openrosa.org/javarosa}requiredMsg': "jr:itext('/data/edad:requiredMsg')", '{http://openrosa.org/javarosa}constraintMsg': "jr:itext('/data/edad:constraintMsg')"}None
2020-05-15T08:03:42     INFO    attrib type isint
2020-05-15T08:03:42     INFO    first attributeedadNone
2020-05-15T08:03:42     INFO    creating new field:edadNone
2020-05-15T08:03:42     INFO    'type'None
2020-05-15T08:03:42     INFO    {'nodeset': '/data/dia', 'type': 'date', '{http://openrosa.org/javarosa}constraintMsg': "jr:itext('/data/dia:constraintMsg')"}None
2020-05-15T08:03:42     INFO    attrib type isdate
2020-05-15T08:03:42     INFO    first attributediaNone
2020-05-15T08:03:42     INFO    creating new field:diaNone
2020-05-15T08:03:42     INFO    'type'None
2020-05-15T08:03:42     INFO    {'nodeset': '/data/GEOMETRY', 'type': 'geopoint', 'required': 'true()', '{http://openrosa.org/javarosa}requiredMsg': "jr:itext('/data/GEOMETRY:requiredMsg')", '{http://openrosa.org/javarosa}constraintMsg': "jr:itext('/data/GEOMETRY:constraintMsg')"}None
2020-05-15T08:03:42     INFO    attrib type isgeopoint
2020-05-15T08:03:42     INFO    first attributeGEOMETRYNone
2020-05-15T08:03:42     INFO    {'nodeset': '/data/mate', 'type': 'select1', 'required': 'true()', '{http://openrosa.org/javarosa}requiredMsg': "jr:itext('/data/mate:requiredMsg')", '{http://openrosa.org/javarosa}constraintMsg': "jr:itext('/data/mate:constraintMsg')"}None
2020-05-15T08:03:42     INFO    attrib type isselect1
2020-05-15T08:03:42     INFO    first attributemateNone
2020-05-15T08:03:42     INFO    creating new field:mateNone
2020-05-15T08:03:42     INFO    'type'None
2020-05-15T08:03:42     INFO    {'nodeset': '/data/tipo_mate', 'type': 'select', 'relevant': "(selected(/data/mate, 'si'))", '{http://openrosa.org/javarosa}constraintMsg': "jr:itext('/data/tipo_mate:constraintMsg')"}None
2020-05-15T08:03:42     INFO    attrib type isselect
2020-05-15T08:03:42     INFO    first attributetipo_mateNone
2020-05-15T08:03:42     INFO    creating new field:tipo_mateNone
2020-05-15T08:03:42     INFO    'type'None
2020-05-15T08:03:42     INFO    {'nodeset': '/data/imagen', 'type': 'binary', '{http://openrosa.org/javarosa}constraintMsg': "jr:itext('/data/imagen:constraintMsg')"}None
2020-05-15T08:03:42     INFO    attrib type isbinary
2020-05-15T08:03:42     INFO    first attributeimagenNone
2020-05-15T08:03:42     INFO    creating new field:imagenNone
2020-05-15T08:03:42     INFO    'type'None
2020-05-15T08:03:42     INFO    now setting exernal resource widgtNone
2020-05-15T08:03:42     INFO    {'nodeset': '/data/usuario', 'type': 'string', '{http://openrosa.org/javarosa}preload': 'property', '{http://openrosa.org/javarosa}preloadParams': 'username'}None
2020-05-15T08:03:42     INFO    attrib type isstring
2020-05-15T08:03:42     INFO    first attributeusuarioNone
2020-05-15T08:03:42     INFO    creating new field:usuarioNone
2020-05-15T08:03:42     INFO    Reached HiddenNone
2020-05-15T08:03:42     INFO    setting hidden widgetNone
2020-05-15T08:03:42     INFO    {'nodeset': '/data/fecha', 'type': 'date', '{http://openrosa.org/javarosa}preload': 'date', '{http://openrosa.org/javarosa}preloadParams': 'today'}None
2020-05-15T08:03:42     INFO    attrib type isdate
2020-05-15T08:03:42     INFO    first attributefechaNone
2020-05-15T08:03:42     INFO    creating new field:fechaNone
2020-05-15T08:03:42     INFO    Reached HiddenNone
2020-05-15T08:03:42     INFO    setting hidden widgetNone
2020-05-15T08:03:42     INFO    {'nodeset': '/data/start_time', 'type': 'dateTime', '{http://openrosa.org/javarosa}preload': 'timestamp', '{http://openrosa.org/javarosa}preloadParams': 'start'}None
2020-05-15T08:03:42     INFO    attrib type isdateTime
2020-05-15T08:03:42     INFO    first attributestart_timeNone
2020-05-15T08:03:42     INFO    creating new field:start_timeNone
2020-05-15T08:03:42     INFO    Reached HiddenNone
2020-05-15T08:03:42     INFO    setting hidden widgetNone
2020-05-15T08:03:42     INFO    {'nodeset': '/data/end_time', 'type': 'dateTime', '{http://openrosa.org/javarosa}preload': 'timestamp', '{http://openrosa.org/javarosa}preloadParams': 'end'}None
2020-05-15T08:03:42     INFO    attrib type isdateTime
2020-05-15T08:03:42     INFO    first attributeend_timeNone
2020-05-15T08:03:42     INFO    creating new field:end_timeNone
2020-05-15T08:03:42     INFO    Reached HiddenNone
2020-05-15T08:03:42     INFO    setting hidden widgetNone
2020-05-15T08:03:42     INFO    'type'None
2020-05-15T08:03:42     INFO    number of submissions are3
2020-05-15T08:03:42     INFO    server lastID isuuid:b6c0c7d0-26a7-47ad-8f59-20d2c35cc93a
2020-05-15T08:03:42     INFO    first DownloadNone
2020-05-15T08:03:42     INFO    downloadingNone
2020-05-15T08:03:42     INFO    http://rpgeo.ddns.net:8080/ODKAggregate/view/downloadSubmissionNone
2020-05-15T08:03:42     INFO    errorNone
2020-05-15T08:03:42     INFO    value isNone
2020-05-15T08:03:42     INFO    value isRojas
2020-05-15T08:03:42     INFO    value isMara
2020-05-15T08:03:42     INFO    value is30
2020-05-15T08:03:42     INFO    value is2020-05-14
2020-05-15T08:03:42     INFO    value is-31.0119760200 -64.0780700900 534.1428222656 3.2160000801
2020-05-15T08:03:42     INFO    value issi
2020-05-15T08:03:42     INFO    value isamargo hierbas
2020-05-15T08:03:42     INFO    value is1589495688199.jpg
2020-05-15T08:03:42     INFO    Download url ishttp://rpgeo.ddns.net:8080/ODKAggregate/view/binaryData?blobKey=build_Conociendo-odk-rev_1589495584%5B%40version%3Dnull+and+%40uiVersion%3Dnull%5D%2Fdata%5B%40key%3Duuid%3Acea3b7e3-cc1f-4ab1-a3fa-53e41c3f49a2%5D%2Fimagen%5B%40ordinal%3D1%5D&as_attachment=true
2020-05-15T08:03:42     INFO    value istaller
2020-05-15T08:03:42     INFO    value is2020-05-14
2020-05-15T08:03:42     INFO    value is2020-05-14T19:33:54.135-03:00
2020-05-15T08:03:42     INFO    value is2020-05-14T19:34:52.112-03:00
2020-05-15T08:03:42     INFO    value isuuid:cea3b7e3-cc1f-4ab1-a3fa-53e41c3f49a2
2020-05-15T08:03:42     INFO    http://rpgeo.ddns.net:8080/ODKAggregate/view/downloadSubmissionNone
2020-05-15T08:03:42     INFO    errorNone
2020-05-15T08:03:42     INFO    http://rpgeo.ddns.net:8080/ODKAggregate/view/downloadSubmissionNone
2020-05-15T08:03:43     INFO    errorNone
2020-05-15T08:03:43     INFO    before Update LayerNone
2020-05-15T08:03:43     INFO    table have some dataNone
2020-05-15T08:03:43     INFO    ODKUUIDNone
2020-05-15T08:03:43     INFO    []None
2020-05-15T08:03:43     INFO    geofield isGEOMETRY
2020-05-15T08:03:43     INFO    {'meta': None, 'apellido': 'Rojas', 'nombre': 'Mara', 'edad': '30', 'dia': '2020-05-14', 'GEOMETRY': '-31.0119760200 -64.0780700900 534.1428222656 3.2160000801', 'mate': 'si', 'tipo_mate': 'amargo hierbas', 'imagen': 'http://rpgeo.ddns.net:8080/ODKAggregate/view/binaryData?blobKey=build_Conociendo-odk-rev_1589495584%5B%40version%3Dnull+and+%40uiVersion%3Dnull%5D%2Fdata%5B%40key%3Duuid%3Acea3b7e3-cc1f-4ab1-a3fa-53e41c3f49a2%5D%2Fimagen%5B%40ordinal%3D1%5D', 'usuario': 'taller', 'fecha': '2020-05-14', 'start_time': '2020-05-14T19:33:54.135-03:00', 'end_time': '2020-05-14T19:34:52.112-03:00', 'ODKUUID': 'uuid:cea3b7e3-cc1f-4ab1-a3fa-53e41c3f49a2'}None
2020-05-15T08:03:43     INFO    odk id isuuid:cea3b7e3-cc1f-4ab1-a3fa-53e41c3f49a2
2020-05-15T08:03:43     INFO    {'meta': None, 'apellido': 'Rojas', 'nombre': 'Mara', 'edad': '30', 'dia': '2020-05-14', 'GEOMETRY': '-31.0119760200 -64.0780700900 534.1428222656 3.2160000801', 'mate': 'si', 'tipo_mate': 'amargo hierbas', 'imagen': 'http://rpgeo.ddns.net:8080/ODKAggregate/view/binaryData?blobKey=build_Conociendo-odk-rev_1589495584%5B%40version%3Dnull+and+%40uiVersion%3Dnull%5D%2Fdata%5B%40key%3Duuid%3Acea3b7e3-cc1f-4ab1-a3fa-53e41c3f49a2%5D%2Fimagen%5B%40ordinal%3D1%5D', 'usuario': 'taller', 'fecha': '2020-05-14', 'start_time': '2020-05-14T19:33:54.135-03:00', 'end_time': '2020-05-14T19:34:52.112-03:00', 'ODKUUID': 'uuid:cea3b7e3-cc1f-4ab1-a3fa-53e41c3f49a2'}None
2020-05-15T08:03:43     INFO    POINT(-64.07807009 -31.01197602)None
2020-05-15T08:03:43     INFO    geom is
2020-05-15T08:03:43     INFO    {'meta': None, 'apellido': 'Rojas', 'nombre': 'Mara', 'edad': '20', 'dia': '2020-05-16', 'GEOMETRY': '-31.0119784600 -64.0780564300 534.1218261719 3.2160000801', 'mate': 'si', 'tipo_mate': 'amargo hierbas', 'imagen': None, 'usuario': 'taller', 'fecha': '2020-05-14', 'start_time': '2020-05-14T19:43:18.592-03:00', 'end_time': '2020-05-14T19:51:06.286-03:00', 'ODKUUID': 'uuid:e88cd799-2c7d-43e5-9493-579cfb6cea5e'}None
2020-05-15T08:03:43     INFO    odk id isuuid:e88cd799-2c7d-43e5-9493-579cfb6cea5e
2020-05-15T08:03:43     INFO    {'meta': None, 'apellido': 'Rojas', 'nombre': 'Mara', 'edad': '20', 'dia': '2020-05-16', 'GEOMETRY': '-31.0119784600 -64.0780564300 534.1218261719 3.2160000801', 'mate': 'si', 'tipo_mate': 'amargo hierbas', 'imagen': None, 'usuario': 'taller', 'fecha': '2020-05-14', 'start_time': '2020-05-14T19:43:18.592-03:00', 'end_time': '2020-05-14T19:51:06.286-03:00', 'ODKUUID': 'uuid:e88cd799-2c7d-43e5-9493-579cfb6cea5e'}None
2020-05-15T08:03:43     INFO    POINT(-64.07805643 -31.01197846)None
2020-05-15T08:03:43     INFO    geom is
2020-05-15T08:03:43     INFO    {'meta': None, 'apellido': 'G', 'nombre': 'H', 'edad': '5', 'dia': '2020-05-22', 'GEOMETRY': '-31.0119552900 -64.0780424100 533.5878906250 8.5760002136', 'mate': 'si', 'tipo_mate': 'azucar', 'imagen': None, 'usuario': 'taller', 'fecha': '2020-05-14', 'start_time': '2020-05-14T19:51:16.024-03:00', 'end_time': '2020-05-14T19:51:57.531-03:00', 'ODKUUID': 'uuid:b6c0c7d0-26a7-47ad-8f59-20d2c35cc93a'}None
2020-05-15T08:03:43     INFO    odk id isuuid:b6c0c7d0-26a7-47ad-8f59-20d2c35cc93a
2020-05-15T08:03:43     INFO    {'meta': None, 'apellido': 'G', 'nombre': 'H', 'edad': '5', 'dia': '2020-05-22', 'GEOMETRY': '-31.0119552900 -64.0780424100 533.5878906250 8.5760002136', 'mate': 'si', 'tipo_mate': 'azucar', 'imagen': None, 'usuario': 'taller', 'fecha': '2020-05-14', 'start_time': '2020-05-14T19:51:16.024-03:00', 'end_time': '2020-05-14T19:51:57.531-03:00', 'ODKUUID': 'uuid:b6c0c7d0-26a7-47ad-8f59-20d2c35cc93a'}None
2020-05-15T08:03:43     INFO    POINT(-64.07804241 -31.01195529)None
2020-05-15T08:03:43     INFO    geom is

**Python error tab**
2020-05-15T08:03:43     WARNING    Traceback (most recent call last):
              File "C:/Users/Mara/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QRealTime\QRealTime.py", line 278, in importData
              service.importData(layer,selectedForm,True)
              File "C:/Users/Mara/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QRealTime\QRealTime_dialog.py", line 271, in importData
              self.collectData(layer,self.formKey,importData,self.topElement,self.version,self.geoField)
              File "C:/Users/Mara/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QRealTime\QRealTime_dialog.py", line 427, in collectData
              self.updateLayer(layer,remoteTable,geoField)
              File "C:/Users/Mara/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QRealTime\QRealTime_dialog.py", line 504, in updateLayer
              self.iface.messageBar().pushWarning(self.tag, self.tr("Can't find '%s' field") % fieldError)
             TypeError: not all arguments converted during string formatting
             

**To Reproduce**
1. Go to 'Import' doing right click on a empy point layer 
2. Click on 'Accept' to import the form that it is in the Server.
3. See error

**Expected behavior**
Data in both attribute table and canvas (geometry).

**Screenshots**
![Data_ODKAggregate](https://user-images.githubusercontent.com/54945279/82045198-11b34700-9685-11ea-8254-d720e2404f09.png)
![Layer_AttributeTable_Empty](https://user-images.githubusercontent.com/54945279/82045225-1bd54580-9685-11ea-9723-7233408ed674.png)

please complete the following information):
 - OS: [Windows 10 Pro]
 - QGIS Version [3.6, 3.8]
 - Plugin Version [3.11 The experimental one]

**Additional context**
- If I import the collected data as .csv in QGIS a can see it correctly. 
- In the stable version its works.

**Comment by shivareddyiirs** [comment]
Thanks @maracarolinarojas . Please verify if issue is resolved. Feel free to reopen if issue still persist.
Check latest version of the plugin i.e 3.12

**Comment by poVoq** [comment]
I get a similar error with qrealtime experimental 4.2.1 and kobo.humanitarianresponse.info.

The structure of the attribute table is downloaded on import but none of the actual submission data.

**Comment by shivareddyiirs** [comment]
Just check if last submission field have some value which is greater or equal to the latest submission id. 

I think this is the main reason. Whenever we switch from one layer to another , last submission id of prev sync/import  operation can create problem.
