### ISSUE TITLE
Cant "Make Online" a Geopackage layer

### ISSUE THREAD

**Issue by mygiano** [shivareddyiirs/QRealTime#63]
Error after Click "Make Online" for my geopackage layer

2021-05-20T15:11:39     WARNING    Traceback (most recent call last):
              File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QRealTime\QRealTime.py", line 399, in sendForm
              fieldDict= self.getFieldsModel(layer)
              File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QRealTime\QRealTime.py", line 446, in getFieldsModel
              fieldDef['type'] = QVariantToODKtype(field.type())
              File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QRealTime\QRealTime.py", line 92, in QVariantToODKtype
              raise AttributeError("Can't cast QVariant to ODKType: " + q_type)
             TypeError: can only concatenate str (not "Type") to str

 - OS: [e.g. Windows 10]
 - QGIS Version [e.g. 3.18.2]
 - Plugin Version [e.g. 3.8]

**Comment by shivareddyiirs** [comment]
Please confirm if this issue is there in experimental version 3.15 too.

Thanks for your feedback

**Comment by mygiano** [comment]
thank you, fully work in experimental 3.15

**Comment by shivareddyiirs** [comment]
Closing this issue then. Would soon be making experimental version stable. 

New experimental version would be with added support to ODK central.
